### ISSUE TITLE
setup 設定出現錯誤

### ISSUE THREAD

**Issue by amyyenjungpeng** [ktlast/punch_in_icehrm#2]
目前的 setup 寫法會出現，`若 google-chrome 版本較新，但 chromedriver 尚未有同樣的版號可下載時` 會跳錯

**Comment by amyyenjungpeng** [comment]
https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable

我先手動從這個 repo 載好 chromedirver 對應的版本，再執行 setup

**Comment by ktlast** [comment]
ok 這個我自己的環境應該可以測
之後更新 Q

**Comment by ktlast** [comment]
目前打算在 `setup` script 加版本參數，沒指定就用最新；
如果真的是版本問題至少可以快速帶參數解決

**Comment by ktlast** [comment]
@amyyenjungpeng 改版中，參考 `dev` branch

目前打算就先把版本寫死，先用你說的 `99.0.4844.51` (雖然還有錯誤)
